#!/usr/bin/env bash

if [[ -z "$EXPORTPACKTARGETDIR" ]]; then
    echo "Need to specify target directory as EXPORTPACKTARGETDIR=dir" >&2
    exit 1
fi

export MAKECONF="${OBJ_BASE}/source/tool/bin/makeconf"

export TARGETDIR="$EXPORTPACKTARGETDIR"
source <("$MAKECONF" "$OBJ_BASE" ARCH QEMU_PATH QEMU_OPTIONS MODULE_SEARCH_PATH BUILDDIR_SEARCHPATH)

export QEMU="$MAKECONF_QEMU_PATH"
export QEMU_OPTIONS="$MAKECONF_QEMU_OPTIONS"
export IMAGE_FILE="bootstrap.elf"
export SEARCHPATH="${MODULE_SEARCH_PATH}:${SEARCHPATH}:${MAKECONF_MODULE_SEARCH_PATH}:${MAKECONF_BUILDDIR_SEARCHPATH}"
export L4DIR="$(realpath "${OBJ_BASE}/source")"
: ${ENTRY:=${E}}; export ENTRY
: ${ARCH:="$MAKECONF_ARCH"}; export ARCH

exec ${L4DIR}/tool/bin/genexportpack \
     --timeout=${GRUB_TIMEOUT:-0} \
     --grubpathprefix="${GRUB_PATHPREFIX}" \
     --grubentrytitle="${GRUB_ENTRY_TITLE:-}" \
     "${MODULES_LIST}" "$EXPORTPACKTARGETDIR" "$ENTRY"
