#!/usr/bin/env bash

IMAGEBUILDER_MKIMAGE_SUFFIX="uimage"
declare -a IMAGEBUILDER_MKIMAGE_FLAGS=()

if [[ -n "${TARGET_IMAGE}" ]] ; then
    TARGET_MKIMAGE=${TARGET_IMAGE}
    TARGET_IMAGE="${TARGET_IMAGE%.${IMAGEBUILDER_MKIMAGE_SUFFIX}}.raw"
fi

source "$(dirname "$0")/_mkimage_build.sh.inc"
