entry[no-defaults] [% entryname %]
kernel [% kernel.name %] [% kernel.args %]
bootstrap [% bootstrap.name %] [% bootstrap.args %]
sigma0 [% rootpager.name %]
[% UNLESS roottask.omit %]roottask [% roottask.name %] [% roottask.args %][% END %]
[% UNLESS itas.omit %]module l4re[% END %]
[% FOREACH m IN extra_modules %]
module[% IF m.defined('opts') %][% "[" %][% m.opts %][% "]" %][% END %] [% m.name %] [% m.is_rw ? ":rw" : "" %]
[%- END %]
