entry[no-defaults] [% entryname %]
kernel [% kernel.name %] [% kernel.args %]
bootstrap [% bootstrap.name %] [% bootstrap.args %]
sigma0 [% rootpager.name %]
[%# cpu_firmware must not be the first or second module,
    beccause when using a grubcfg they are special %]
[% UNLESS roottask.omit && !cpu_firmware.file %]roottask [% roottask.name %] [% roottask.args %][% END %]
[% UNLESS itas.omit && !cpu_firmware.file %]module l4re[% END %]
[% IF cpu_firmware.file -%]
module[fname=cpu_firmware.bin] [% cpu_firmware.file %]
[% END -%]
[% FOREACH m IN extra_modules %]
module[% IF m.defined('opts') %][% "[" %][% m.opts %][% "]" %][% END %] [% m.name %] [% m.is_rw ? ":rw" : "" %]
[%- END %]
