# vim:set ft=make:

PLATFORM_NAME        = "Generic Arm Platform"
PLATFORM_ARCH        = arm arm64
IS_GEN_DT_PLATFORM   = y
PLATFORM_RAM_BASE    = 0

# For the generic platform we really need a PIE bootstrap. Everything else
# is specific customization.
ifeq ($(PLATFORM_TYPE),arm_gen)
  ifeq ($(or $(CONFIG_BID_PIE_VOLUNTARY),$(CONFIG_BID_PIE_ALL)),)
    $(error Platform 'arm_gen' requires a PIE build of L4Re.)
  endif
endif
