# vim:set ft=make:

PLATFORM_NAME        = "Generic Arm Platform"
PLATFORM_ARCH        = arm arm64
IS_GEN_DT_PLATFORM   = y

_need_ram_base=$(filter $(MAKECMDGOALS),uimage itb)
$(if $(_need_ram_base),,$(eval PLATFORM_RAM_BASE = 0))

# For the generic platform we really need a PIE bootstrap. Everything else
# is specific customization.
ifeq ($(PLATFORM_TYPE),arm_gen)
  ifeq ($(or $(CONFIG_BID_PIE_VOLUNTARY),$(CONFIG_BID_PIE_ALL)),)
    $(error Platform 'arm_gen' requires a PIE build of L4Re.)
  endif
endif

_missing_ram_base=$(if $(_need_ram_base),$(if $(PLATFORM_RAM_BASE),,missing))
$(if $(_missing_ram_base),$(error \
  Need to specify PLATFORM_RAM_BASE on the command-line for the Generic Arm platform))
