PLATFORM_NAME        = "Generic Arm Platform"
PLATFORM_ARCH        = arm arm64

_need_ram_base=$(filter $(MAKECMDGOALS),elfimage uimage efiimage itb)
_missing_ram_base=$(if $(_need_ram_base),$(if $(PLATFORM_RAM_BASE),,missing))
$(if $(_missing_ram_base),$(error \
  Need to specify PLATFORM_RAM_BASE on the command-line for the Generic Arm platform))
